INSERT INTO Parts VALUES (1,'Microprocessor','Intel AMD Chip','LG','Refurbished',489,89.39);
INSERT INTO Parts VALUES (2,'Motherboard','ATI Chip Board','Dell','Used',934,44.04);
INSERT INTO Parts VALUES (3,'Memory','DDR234 RAM','Acer','Refurbished',135,52.75);
INSERT INTO Parts VALUES (4,'Chassis Case','Desktop Case','Vizio','Refurbished',574,61.76);
INSERT INTO Parts VALUES (5,'Hard Drive','Magnetic Hard Drive','Fujitsu','Used',77,80.88);
INSERT INTO Parts VALUES (6,'CD ROM','Rewriteable DVD CD Drive','Sony','Used',865,83.62);
INSERT INTO Parts VALUES (7,'Video Card','Desktop Video Card','Zoostorm','New',205,42.60);
INSERT INTO Parts VALUES (8,'Sound Card','Desktop Sound Card','Hewlett-Packard','New',524,42.02);
INSERT INTO Parts VALUES (9,'Mouse','Wireless Mouse','Logitech','New',517,90.08);
INSERT INTO Parts VALUES (10,'Monitor','LCD Screen','Asus','Refurbished',317,99.99);
INSERT INTO Parts VALUES (11,'Operating System','Windows OS','Windows','New',990,74.24);
INSERT INTO Parts VALUES (12,'AntiVirus Software','Virus Protection','Kaspersky','New',226,53.32);
INSERT INTO Parts VALUES (13,'Microsoft Office','Word Powerpoint Excell Access','Microsoft','New',165,60.00);
INSERT INTO Parts VALUES (14,'SSD Hard Drive','250GB Hard Drive','IBM','New',406,64.12);
INSERT INTO Parts VALUES (15,'Monitor','LCD Screen','Asus','Refurbished',317,99.99);
INSERT INTO Parts VALUES (16,'Operating System','Windows OS','Windows','New',990,74.24);
INSERT INTO Parts VALUES (17,'AntiVirus Software','Virus Protection','Kaspersky','New',226,53.32);
INSERT INTO Parts VALUES (18,'Microsoft Office','Word Powerpoint Excell Access','Microsoft','New',165,60.00);
INSERT INTO Parts VALUES (19,'SSD Hard Drive','250GB Hard Drive','IBM','New',406,64.12);
INSERT INTO Parts VALUES (20,'Keyboard','Ergonomic Keyboard','LG','Used',637,36.50);
commit;